### ISSUE TITLE
Please add usage info

### ISSUE THREAD

**Issue by sc0ttj** [trapd00r/File-LsColor#8]
Please add usage info for idiots like me know how to use this.

**Comment by nerd190** [comment]
+1 Yes please!
I have tried moving it to my /lib/perl5/5.3.../ directory, then exiting terminal, upon re-entry I cannot use these functions though.
Do I move it to my ~/.local/lib instead of perl's lib directory?
Or my system lib directory?
(Must be a scott thing @sc0ttj ? 😂 )

THANK YOU SO MUCH DEV! FOR BRINGING COLOR TO MY TERMINAL!
had no problems with lscolors, just adding this lib! 😥

**Comment by trapd00r** [comment]
The easiest is to use cpanm: https://metacpan.org/pod/App::cpanminus#Installing-to-system-perl

Then, just do:

$ cpanm File::LsColor
